sudo: false
language: java
jdk:
  - oraclejdk8

before_script:
  - curl -O -L https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter/releases/download/v1.0-snapshot/cognizant-intelligent-test-scripter-1.0-SNAPSHOT-setup.zip
  - unzip cognizant-intelligent-test-scripter-1.0-SNAPSHOT-setup.zip "cognizant-intelligent-test-scripter-1.0-SNAPSHOT/*"
  - ls

script: "./run.command -help"
